server:
  port: 8000

spring:
  resources:
    static-locations: classpath:/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/south_door
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5

# mybatis
mybatis:
  type-aliases-package: org.hellosix.door.dao
  configuration:
    map-underscore-to-camel-case: true

# south door configuration
south-door:
  admin:
    user-name: admin
    password: admin
  # max proxy size
  max-proxy-size: 200
  # default: http, other: tcp
  proxy-type: http
  data:
    # Absolute path: site index image
    site-image-path: E://project/hellosix/south-door/src/main/resources/public/site/
